<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Actions_Btn_Obj</name>
   <tag></tag>
   <elementGuidId>afe181b6-0d66-4977-b613-0a065904171a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table//td[@title='Actions']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//td[@title='Actions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[@title='Actions']</value>
   </webElementProperties>
</WebElementEntity>
