<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Requirement_Option</name>
   <tag></tag>
   <elementGuidId>3c8ae35e-4651-4516-8f8c-543e141ad716</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a//label[text()='Requirement...']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
