<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WorkflowTemplate_Obj</name>
   <tag></tag>
   <elementGuidId>44dd2f9e-1f18-403a-98fe-5ed5ae73f3f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@name=&quot;ProgramWorkflowTemplate&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@name=&quot;ProgramWorkflowTemplate&quot;]</value>
   </webElementProperties>
</WebElementEntity>
