<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BCMProjectTeamInboxBCMElements_Obj</name>
   <tag></tag>
   <elementGuidId>e46bb8ff-1f1f-4072-adf7-0b7070a5aa9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name=&quot;BCMProjectTeamInboxBCMElements&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
