<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IP_Classification_Obj</name>
   <tag></tag>
   <elementGuidId>461e156c-1f3c-4761-a59b-c8cb4cb050c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@name=&quot;IPclassfn&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@name=&quot;IPclassfn&quot;]</value>
   </webElementProperties>
</WebElementEntity>
