<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_company_Obj</name>
   <tag></tag>
   <elementGuidId>c0eb069e-546e-4636-886b-6f95d40d3180</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@name=&quot;emxTableRowId&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@name=&quot;emxTableRowId&quot;])[1]</value>
   </webElementProperties>
</WebElementEntity>
