<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DM_button_Obj</name>
   <tag></tag>
   <elementGuidId>60f7ab4b-eea1-4ca4-a10e-44735591cc7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id=&quot;DMCMyDesk&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id=&quot;DMCMyDesk&quot;]</value>
   </webElementProperties>
</WebElementEntity>
