<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Get_Function_Obj</name>
   <tag></tag>
   <elementGuidId>a3759e8b-27d2-4a04-9b9e-35fb4d22aee1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//table[@id=&quot;TIMembers&quot;]//tr[2])//td[7]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
