<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Membership_Tab_Obj</name>
   <tag></tag>
   <elementGuidId>4135b62b-afa6-42cc-bf86-d75a9242c086</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr//td[text()='Membership']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tr//td[text()='Membership']</value>
   </webElementProperties>
</WebElementEntity>
