<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FileVersion_Obj</name>
   <tag></tag>
   <elementGuidId>2a2f520d-4bc3-4a7c-9ac2-951cfb06a637</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[contains(@name,&quot;cmbFileVersion&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[contains(@name,&quot;cmbFileVersion&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
