<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ChangeState_Obj</name>
   <tag></tag>
   <elementGuidId>c40b5746-d44c-432a-a508-494a392ffcb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[contains(@src,&quot;iconActionPromote.gif&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[contains(@src,&quot;iconActionPromote.gif&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
