<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LifeCycleTab_Obj</name>
   <tag></tag>
   <elementGuidId>6115d3cc-c506-46e8-a60d-6615c667e11d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[text()=&quot;Lifecycle&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[text()=&quot;Lifecycle&quot;]</value>
   </webElementProperties>
</WebElementEntity>
