<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TIDocumentLifecycle_Iframe_Obj</name>
   <tag></tag>
   <elementGuidId>c23c3d59-7506-42c1-b6c5-a34d732e91ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@name=&quot;TIDocumentLifecycle&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//iframe[@name=&quot;TIDocumentLifecycle&quot;]</value>
   </webElementProperties>
</WebElementEntity>
