<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Function_Obj</name>
   <tag></tag>
   <elementGuidId>fb3e6cac-c12c-4fa2-8404-1b8a6f99fea4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@name=&quot;27529.43057.36069.4605&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@name=&quot;27529.43057.36069.4605&quot;]</value>
   </webElementProperties>
</WebElementEntity>
