<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProgramDescription_Obj</name>
   <tag></tag>
   <elementGuidId>915bce77-3a2f-49fb-9ff9-7882f0dbf61d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@name=&quot;ProgramDescription&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[@name=&quot;ProgramDescription&quot;]</value>
   </webElementProperties>
</WebElementEntity>
