<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SecondaryOwner_Obj</name>
   <tag></tag>
   <elementGuidId>a8c696dc-e471-46b0-bc0e-d203b3003839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='TISecondaryOwnerText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='TISecondaryOwnerText']</value>
   </webElementProperties>
</WebElementEntity>
