<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WorkflowTemplate_Obj</name>
   <tag></tag>
   <elementGuidId>a218665b-c728-4e95-a227-928935ed3cf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@name=&quot;ProgramWorkflowTemplate&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@name=&quot;ProgramWorkflowTemplate&quot;]</value>
   </webElementProperties>
</WebElementEntity>
