<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Project.gif_Obj</name>
   <tag></tag>
   <elementGuidId>39e53dbc-9a36-445f-8f41-ba8bb05b291f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td//input[@name=&quot;SourceProject&quot;]/following::a//img[@src=&quot;../common/images/iconActionSearch.gif&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
