<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UserID1_Obj</name>
   <tag></tag>
   <elementGuidId>826dddfe-791e-4992-8d52-62bf0d96df14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//table[@id=&quot;BCMProjectTeamMembers&quot;]//input[@name=&quot;emxTableRowId&quot;])[1]/../../td[4]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
