<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UserID2_Obj</name>
   <tag></tag>
   <elementGuidId>c4247ac2-63c3-4ad6-b88c-22d8acd803fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//table[@id=&quot;BCMProjectTeamMembers&quot;]//input[@name=&quot;emxTableRowId&quot;])[3]/../../td[4]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
