<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AssociatedSchema_Obj</name>
   <tag></tag>
   <elementGuidId>491f2b32-4496-4187-8a50-77f8f1b1f685</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@name=&quot;AssociatedSchema&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@name=&quot;AssociatedSchema&quot;]</value>
   </webElementProperties>
</WebElementEntity>
