<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Member_Obj</name>
   <tag></tag>
   <elementGuidId>dd28834c-f59e-4c21-a4c6-9799ce58e3bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@name=&quot;li_BCMProjectTeamsMembership&quot;]//label[text()='Members/Access']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
