<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WorkflowTemplate_Obj</name>
   <tag></tag>
   <elementGuidId>4f781aa6-6bd2-421b-a290-b89bac0fad5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@name=&quot;ProgramWorkflowTemplate&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@name=&quot;ProgramWorkflowTemplate&quot;]</value>
   </webElementProperties>
</WebElementEntity>
