<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Assigned_To_Fix</name>
   <tag></tag>
   <elementGuidId>aef1cf32-6d41-4ad8-a67a-15b350e8b684</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;ShowAssigneeSelection()&quot;]//img[@src=&quot;../common/images/iconActionKeySearch.gif&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
