<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GrantComponentLAAHA_Obj</name>
   <tag></tag>
   <elementGuidId>ce6c8617-8d3c-4f8f-b0b3-7006d783da73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name=&quot;GrantCompLevAAHA&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name=&quot;GrantCompLevAAHA&quot;]</value>
   </webElementProperties>
</WebElementEntity>
