<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BCMProjectConfigDetailsStateRoutes_Frame_Obj</name>
   <tag></tag>
   <elementGuidId>52a3055b-38d4-4ed7-8126-bd4a19b2ac23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@name = 'BCMProjectConfigDetailsStateRoutes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BCMProjectConfigDetailsStateRoutes</value>
   </webElementProperties>
</WebElementEntity>
