<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BCMProjectConfigDetailsTeamAutoAssign_Frame</name>
   <tag></tag>
   <elementGuidId>870cb7c6-90fc-483f-8828-304dd1dbc770</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name=&quot;BCMProjectConfigDetailsTeamAutoAssign&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
