<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DetailsDisplay_Iframe_Obj</name>
   <tag></tag>
   <elementGuidId>9ab200e9-4dc1-431a-af4d-db23660e89ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@name=&quot;detailsDisplay&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//iframe[@name=&quot;detailsDisplay&quot;]</value>
   </webElementProperties>
</WebElementEntity>
