<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_Display_Iframe_Obj</name>
   <tag></tag>
   <elementGuidId>cdd4fba9-dc79-4226-b4c5-afd44ed9017b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@name=&quot;listDisplay&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name=&quot;listDisplay&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//iframe[@name=&quot;listDisplay&quot;]</value>
   </webElementProperties>
</WebElementEntity>
