<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Get_Project_Text</name>
   <tag></tag>
   <elementGuidId>8621dbc5-d164-4c99-a391-90f50e92d74a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[text()=&quot;Projects&quot;]/..//td[@class=&quot;inputField&quot;]/following-sibling::text()</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
